### ISSUE TITLE
Upgrade from previous version

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/piwigo_ynh#1]
Hi !

I'm using a previous version of Piwigo YNH package, and the upgrade script is not yet available.
Have you planned to provide an upgrade script or I'll have to do the update by hand ?

Thanks,

Léo :fr:

**Comment by JimboJoe** [comment]
Yes, an upgrade script is definitely planned. I was planning to work on this when a new version of Piwigo arises, reasonably not before several weeks.
Yet, I wasn't planning to support migrating from the older version of the app, which was only compatible with YunoHost 2.2. I think it could work on your setup, but I won't be able to test it. You could act then as a beta-tester.
On the other hand, if you don't want to wait, you could try the automatic install provided by Piwigo.
The future YunoHost app upgrade will be based partly on that (but without downloading files from official Piwigo website).

**Comment by LeOSW42** [comment]
Hi !

Here is the way to upgrade manually.

Backup all the MySQL/MariaDB tables with piwigo_ prefix.
Backup the /home/yunohost.app/piwigo directory.
Remove the previous Piwigo app.
Install the new one.
Restore the /home/yunohost.app/piwigo directory.
Restore all the tables except piwigo_config.
Manually restore the piwigo_config field by field to be sure to not replace the version number.

Finished, just remember to add 777 access rights on the /home/yunohost.app/piwigo directory.

**Comment by JimboJoe** [comment]
Thanks for that!
For the upgrade script, we'll need to use part of Piwigo upgrade classes anyway, at least because database schema may change in a future version.
I'll let the issue open until the upgrade script is done, because YunoHost in not intended for us geek only ;-)
