### ISSUE TITLE
Your application has been elected to become official !

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/piwigo_ynh#10]
Hello, 
Since the last week, the community members have voted to elect the next two future official applications.
(https://forum.yunohost.org/t/elis-les-futures-apps-officielles-elect-the-next-official-apps/3484)

Today, we announce to you that your app has been chosen to become official. To be sure that you agree, we need a confirmation from you within 2 weeks. 

By entering in the official group of application, you will have to keep maintaining your application. You will have to create PR before commiting to the master branche and your PRs will have to be reviewed by the Apps Group of Yunohost following our guidline. Of course, you will get help from the App Group to help you maintaining this application.

No confirmation of you means that you disagree with the decision of the community and another application will join the official group instead of piwigo.

Thanks,
The Apps Group

**Comment by JimboJoe** [comment]
Great!
Closing as already taken into account in issue https://github.com/YunoHost-Apps/piwigo_ynh/issues/11
