### ISSUE TITLE
"LDAP extension not loaded" on login

### ISSUE THREAD

**Issue by obrenckle** [YunoHost-Apps/piwigo_ynh#100]
### Describe the bug

After submitting my LDAP username and password when trying to access the app, I get an error page: 

LDAP extension not loaded

### Context

- Hardware: OlinuXino Lime 2
- YunoHost version: 11.0.10.2 (stable)
- I have access to my server: SSH and Webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Fresh Raspbian bullseye install, because there was no Yunohost image at the time
- Using, or trying to install package version/branch: 13.1.0~ynh1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to piwigo app address
   2. Enter LDAP username and password
   3. Click "Submit"
   4. *See error*

### Expected behavior

Log in the app

### Logs

[/var/log/nginx/maindomain.tld-error.log](https://paste.yunohost.org/raw/ukequhanar)

/var/log/debug:
slapd[1459]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16

**Comment by bettyvschmartz** [comment]
The issue seems to be that Piwigo is using PHP 8.0 but the php-ldap extension is only installed for PHP 7.4. You can need to install the ldap extension for PHP 8.0;

`sudo apt install php8.0-ldap`

Restart your nginx and php services and everything should work. 

Fix here is for the PHP extension to be a dependency upon installation of Piwigo.

-- bvs

**Comment by plabuse** [comment]
Hello, I'm not sure, modify on file `_common.sh`

`pkg_dependencies="imagemagick php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-imagick php${YNH_PHP_VERSION}-xml php${YNH_PHP_VERSION}-mbstring php${YNH_PHP_VERSION}-mysqli"
`

by 

`pkg_dependencies="imagemagick php${YNH_PHP_VERSION}-ldap php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-imagick php${YNH_PHP_VERSION}-xml php${YNH_PHP_VERSION}-mbstring php${YNH_PHP_VERSION}-mysqli"
`

French : Je vais essayer de tester.

**Comment by bettyvschmartz** [comment]
That looks like it would do the job.

Looking at the revision history of that file it doesn't look like the ldap extension has ever been a dependency even when `YNH_PHP_VERSION=7.3` was set. So looks like the ldap extension wasn't installed even when using previous PHP versions. 

-- bvs

**Comment by obrenckle** [comment]
Adding the `php8.0-ldap` package fixed it, thank you.

**Comment by ericgaspar** [comment]
Fixed with  #103
