### ISSUE TITLE
Allows to logout

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/piwigo_ynh#2]
Hi all,

In the current implementation of LDAP plugin, it is not possible to logout if you have no access to the administration panel.

Léo

**Comment by JimboJoe** [comment]
This behavior is built in Piwigo (see https://github.com/Piwigo/Piwigo/blob/master/include/menubar.inc.php#L324).
If you log out of the YunoHost portal, you become guest in Piwigo, and if you log-in with another user account, the new user gets logged-in in Piwigo.
The only remaining case I see is with an external (non-LDAP) user, who actually can't logout. The only workaround I see is to visit: <root URL>?act=logout
Do you see any other case?
