### ISSUE TITLE
Connexion / deconnexion problems + administration levels

### ISSUE THREAD

**Issue by galuel** [YunoHost-Apps/piwigo_ynh#32]
I cannot understand how to use piwigo for users access and administrations levels, I found lot of problems and I'm blocked.

When creating a new user "user1" from piwigo administration interface, I connect on it, and then impossible to disconnect from piwigo ! When I disconnect it redirects me to the "galerie photo" interface with the same "user1" connected ! And since that user have not administration access, I cannot reconnect to the administration interface...

When trying to connect directly from Yunohost admin with a user admin, I click then on the piwigo app, and it connects me to the "galerie photo" with the "user1" and not my user admin...

Now I'm blocked...

I tryed then to connect with Chromium instead of Firefox and I succeeded to connect thry Yunohost admin -> user interface -> Piwigo, than connects me to the Piwigo app with my user admin... But when I connect with the "user1", I connot disconnect as well...

I tryed to delete "user1" from another PC, new browser, it worked, and tryed to create it again directly from Yunohost admin, but same problem of impossible to disconnect appear...

YunoHost 3.3.1 - Piwigo installed 19/12/2018 (I cannot find version anywhere, it is official app up to date).

**Comment by JimboJoe** [comment]
Hi,
I've described a workaround in #2 : 

> The only remaining case I see is with an external (non-LDAP) user, who actually can't logout. The only workaround I see is to visit: ?act=logout
