### ISSUE TITLE
bug update plugin

### ISSUE THREAD

**Issue by geek54** [YunoHost-Apps/piwigo_ynh#47]
bug when updating extension Ldap_login2.10c for yunohost v 3.6.5.3

_Warning:  [mysql error 1146] Table 'piwigo.piwigo_ldap_login_config' doesn't exist
select 1 from `piwigo_ldap_login_config` LIMIT 1 in /var/www/piwigo/include/dblayer/functions_mysqli.inc.php on line 856_

**Comment by JimboJoe** [comment]
This has been fixed in the current Testing version. Can you please try it?

**Comment by geek54** [comment]
hello,
update problem. log sent to:
  https://paste.yunohost.org/raw/eyigacipom
I used the command: 
sudo yunohost app upgrade piwigo -u https://github.com/YunoHost-Apps/piwigo_ynh/tree/testing --debug
