### ISSUE TITLE
Error during upgrade, $tmpdir not defined in some cases

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/piwigo_ynh#49]
just to report https://forum.yunohost.org/t/impossible-de-mettre-a-jour-piwigo-from-2-10-1-ynh1-to-2-10-1-ynh2-cant-upgrade-piwigo-from-2-10-1-ynh1-to-2-10-1-ynh2/10531

Indeed, line 162 of the upgrade script, tmpdir seems only set previously in a `if` block

**Comment by roukydesbois** [comment]
Same here!

**Comment by roukydesbois** [comment]
Same here!
