### ISSUE TITLE
Validate quality level 5 conformance

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/piwigo_ynh#5]
This levels needs to be formally assessed as there are residual warnings stated by package_linter :
```
>>>> _COMMON.SH SCRIPT <<<<
✘ Line  21 you should add "sudo" before this command line: 
    chmod 755 $TMPDIR
✘ Line  27 you should add "sudo" before this command line: 
    rm "$archive"
```
These commands manipulates temporary files and folders, for which no administrator privilege is need.

**Comment by maniackcrudelis** [comment]
Ok for me ;)
