### ISSUE TITLE
Version 2.9.0

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/piwigo_ynh#6]
Hi all, salut à tous,

2.9.0 version of Piwigo is out !

Léo

**Comment by JimboJoe** [comment]
Hello, thanks for the notice, the update is in progress:

- rewrite the package to comply with latest standards
- implement full update mecanism based on piwigo upgrade system

Can I have you test it when it's ready (no ETA, holidays coming...)?

**Comment by LeOSW42** [comment]
Yes no problem, I'll test that !
