### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by franc00018** [YunoHost-Apps/piwigo_ynh#75]
### Describe the bug

An automated backup job failed

### Context

- Hardware: VPS bought onlin
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH
- Current package version: 11.5.0~ynh1

### Steps to reproduce

```sh
sudo yunohost backup create --apps piwigo
```

### Expected behavior

I expect the backup to run successfully without error as it has been doing for a long time

### Logs

```bash
Info: Collecting files to be backed up for piwigo...
Info: Loading installation settings...
Info: Declaring files to be backed up...
Warning: Source path '' does not exist
Error: Could not back up piwigo
Info: The operation 'Create a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20210627-034959-backup_create' to get help
Error: Nothing to save
```

Here's my log

[https://paste.yunohost.org/raw/anepejixac
](https://paste.yunohost.org/raw/anepejixac
)

**Comment by roukydesbois** [comment]
If I'm not wrong, the error comes from https://github.com/YunoHost-Apps/piwigo_ynh/blob/f26db379f4b294663d8a6ba4f18aae466202680c/scripts/backup#L31
The backup script looks for an app setting that doesn't exist.

Indeed, this line: https://github.com/YunoHost-Apps/piwigo_ynh/blob/f26db379f4b294663d8a6ba4f18aae466202680c/scripts/install#L124
is from 2 months ago, so new installs have this app setting.

But it hasn't been added in the upgrade script (I'm going to try and create a pull request to add it).

In the meantime, I have run this command:

```
sudo yunohost app setting piwigo datapath -v "/home/yunohost.app/piwigo"
```
and the backup worked. You just need to make sure that piwigo is the correct app name for you (especially if you have multiple instances).

**Comment by franc00018** [comment]
Thanks, it solved my issue. I ran the command to add datapath, then upgraded the application version
